<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
$this->placeholder('url')->delete = $this->urlDelete;
?>
<h1>Protocolos de órgãos</h1>
<table>
<tr>
<td>
<a href="<?=$this->urlEdit?>">Associar protocolo a órgão</a>
</td>
<td>
<form method="post" action="<?=$this->url('protocolo-de-orgao')?>">
<input type="text" name="protocolo">
<input type="submit" value="pesquisar protocolo">
</form>
</td>
<td>
<form method="post" action="<?=$this->url('protocolo-de-orgao')?>">
<input type="text" name="orgao">
<input type="submit" value="pesquisar órgão">
</form>
</td>
</tr>
</table>
<table>
<thead>
<tr>
<th>Protocolo</th>
<th>&nbsp;</th>
<th>Órgão</th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('protocolos-de-orgao.phtml',$this->paginator)?>
</tbody>
</table>
<p>
<?=$this->paginationControl($this->paginator,
'Sliding',
'pagination', ['route' => 'protocolo-de-orgao']); ?>
</p>
<p>
<a href="<?=$this->url('home')?>">Homepage</a>
</p>