<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
$this->placeholder('url')->delete = $this->urlDelete;
?>
<h1>Softwares para IA de órgãos</h1>
<table class="table">
<tr>
<td>
<a href="<?=$this->urlEdit?>">Associar software a órgão</a>
</td>
<td>
<form method="post" action="<?=$this->url('software-de-orgao')?>">
<input type="text" name="software">
<input type="submit" value="pesquisar software">
</form>
</td>
<td>
<form method="post" action="<?=$this->url('software-de-orgao')?>">
<input type="text" name="orgao">
<input type="submit" value="pesquisar órgão">
</form>
</td>
</tr>
</table>
<table class="table">
<thead>
<tr>
<th>Software</th>
<th>&nbsp;</th>
<th>Órgão</th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('softwares-de-orgao.phtml',$this->paginator)?>
</tbody>
</table>
<p>
<?=$this->paginationControl($this->paginator,
'Sliding',
'pagination', [
    'route' => 'software-de-orgao',
    'filtern' => $this->filtern,
    'filterv' => $this->filterv
]); ?>
</p>
<p>
<a href="<?=$this->url('home')?>">Homepage</a>
</p>