<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>
<tr>
<td><?=$this->codigo?></td>
<td><?=$this->escapeHtml($this->nome)?></td>
<td><?=$this->escapeHtml($this->categoria)?></td>
<td><?=$this->escapeHtml($this->licenca)?></td>
<td><?=$this->escapeHtml($this->website)?></td>
<td>
<a href="<?=$this->placeholder('url')->edit . '/'. $this->codigo?>">Editar</a>
</td>
<td>
<a href="<?=$this->placeholder('url')->delete . '/' . $this->codigo?>">Remover</a>
</td>
</tr>