<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->placeholder('url')->edit = $this->urlEdit;
$this->placeholder('url')->delete = $this->urlDelete;
?>
<h1>Softwares de IA</h1>
<table class="table">
<tr>
<td>
<a href="<?=$this->urlEdit?>">Incluir software</a>
</td>
<td>
<form method="post" action="<?=$this->url('software')?>">
<input type="text" name="nome">
<input type="submit" value="pesquisar">
</form>
</td>
</tr>
</table>

<table class="table">
<thead>
<tr>
<th>Código</th>
<th>Software</th>
<th>Categoria</th>
<th>Licença</th>
<th>Website</th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('softwares.phtml',$this->paginator)?>
</tbody>
</table>
<p>
<?=$this->paginationControl($this->paginator,
'Sliding',
'pagination', [
    'route' => 'software',
    'filtern' => $this->filtern,
    'filterv' => $this->filterv
]); ?>
</p>
<p>
<a href="<?=$this->url('home')?>">Homepage</a>
</p>