<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
$this->placeholder('url')->edit = $this->urlEdit;
$this->placeholder('url')->delete = $this->urlDelete;
?>
<h1>Licenças de software</h1>
<table class="table">
<tr>
<td>
<a href="<?=$this->urlEdit?>">Incluir licença</a>
</td>
<td>
<form method="post" action="<?=$this->url('licenca')?>">
<input type="text" name="nome">
<input type="submit" value="pesquisar">
</form>
</td>
</tr>
</table>
<table class="table">
<thead>
<tr>
<th>Código</th>
<th>Categoria</th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('licencas.phtml',$this->paginator)?>
</tbody>
</table>
<p>
<?=$this->paginationControl($this->paginator,
'Sliding',
'pagination', ['route' => 'licenca']); ?>
</p>
<p>
<a href="<?=$this->url('home')?>">Homepage</a>
</p>